version: '3'

services:

  db:
    container_name: ecommerce_db
    image: postgres
    restart: always
    env_file: ./.env
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build: ./app
    container_name: ecommerce_app
    env_file: ./.env
    command: /app/runserver.sh
    volumes:
      - ./app:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

  celery:
    build: ./app
    env_file: ./.env
    command: celery -A config worker -l info
    volumes:
      - ./app:/app
    depends_on:
      - db
      - redis

  celery-beat:
    build: ./app
    env_file: ./.env
    command: celery -A config beat -l info -S django
    volumes:
      - ./app:/app
    depends_on:
      - db
      - redis
      - celery



volumes:
  db_data: